"""empty message

Revision ID: 197a23c12a9d
Revises: b765a29aa46d
Create Date: 2024-04-23 16:04:51.687620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '197a23c12a9d'
down_revision: Union[str, None] = 'b765a29aa46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reminder_completed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reminder_completed')
    # ### end Alembic commands ###
